//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cehars/", ConfigurationName="ServiceReference1.Yeni_Web_Servis")]
    public interface Yeni_Web_Servis {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/operasyon1Request", ReplyAction="http://cehars/Yeni_Web_Servis/operasyon1Response")]
        WindowsFormsApplication6.ServiceReference1.operasyon1Response operasyon1(WindowsFormsApplication6.ServiceReference1.operasyon1Request request);
        
        // CODEGEN: Generating message contract since element name parameter from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/operasyon2Request", ReplyAction="http://cehars/Yeni_Web_Servis/operasyon2Response")]
        WindowsFormsApplication6.ServiceReference1.operasyon2Response operasyon2(WindowsFormsApplication6.ServiceReference1.operasyon2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operasyon1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operasyon1", Namespace="http://cehars/", Order=0)]
        public WindowsFormsApplication6.ServiceReference1.operasyon1RequestBody Body;
        
        public operasyon1Request() {
        }
        
        public operasyon1Request(WindowsFormsApplication6.ServiceReference1.operasyon1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class operasyon1RequestBody {
        
        public operasyon1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operasyon1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operasyon1Response", Namespace="http://cehars/", Order=0)]
        public WindowsFormsApplication6.ServiceReference1.operasyon1ResponseBody Body;
        
        public operasyon1Response() {
        }
        
        public operasyon1Response(WindowsFormsApplication6.ServiceReference1.operasyon1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operasyon1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public operasyon1ResponseBody() {
        }
        
        public operasyon1ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operasyon2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operasyon2", Namespace="http://cehars/", Order=0)]
        public WindowsFormsApplication6.ServiceReference1.operasyon2RequestBody Body;
        
        public operasyon2Request() {
        }
        
        public operasyon2Request(WindowsFormsApplication6.ServiceReference1.operasyon2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operasyon2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parameter;
        
        public operasyon2RequestBody() {
        }
        
        public operasyon2RequestBody(string parameter) {
            this.parameter = parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operasyon2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operasyon2Response", Namespace="http://cehars/", Order=0)]
        public WindowsFormsApplication6.ServiceReference1.operasyon2ResponseBody Body;
        
        public operasyon2Response() {
        }
        
        public operasyon2Response(WindowsFormsApplication6.ServiceReference1.operasyon2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operasyon2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public operasyon2ResponseBody() {
        }
        
        public operasyon2ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Yeni_Web_ServisChannel : WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Yeni_Web_ServisClient : System.ServiceModel.ClientBase<WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis>, WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis {
        
        public Yeni_Web_ServisClient() {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication6.ServiceReference1.operasyon1Response WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis.operasyon1(WindowsFormsApplication6.ServiceReference1.operasyon1Request request) {
            return base.Channel.operasyon1(request);
        }
        
        public string operasyon1() {
            WindowsFormsApplication6.ServiceReference1.operasyon1Request inValue = new WindowsFormsApplication6.ServiceReference1.operasyon1Request();
            inValue.Body = new WindowsFormsApplication6.ServiceReference1.operasyon1RequestBody();
            WindowsFormsApplication6.ServiceReference1.operasyon1Response retVal = ((WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis)(this)).operasyon1(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication6.ServiceReference1.operasyon2Response WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis.operasyon2(WindowsFormsApplication6.ServiceReference1.operasyon2Request request) {
            return base.Channel.operasyon2(request);
        }
        
        public string operasyon2(string parameter) {
            WindowsFormsApplication6.ServiceReference1.operasyon2Request inValue = new WindowsFormsApplication6.ServiceReference1.operasyon2Request();
            inValue.Body = new WindowsFormsApplication6.ServiceReference1.operasyon2RequestBody();
            inValue.Body.parameter = parameter;
            WindowsFormsApplication6.ServiceReference1.operasyon2Response retVal = ((WindowsFormsApplication6.ServiceReference1.Yeni_Web_Servis)(this)).operasyon2(inValue);
            return retVal.Body.@return;
        }
    }
}
