//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication12.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cehars/", ConfigurationName="ServiceReference1.Yeni_Web_Servis")]
    public interface Yeni_Web_Servis {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/ekleRequest", ReplyAction="http://cehars/Yeni_Web_Servis/ekleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.ekleResponse ekle(WindowsFormsApplication12.ServiceReference1.ekleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/sorguRequest", ReplyAction="http://cehars/Yeni_Web_Servis/sorguResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.sorguResponse sorgu(WindowsFormsApplication12.ServiceReference1.sorguRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/guncelleRequest", ReplyAction="http://cehars/Yeni_Web_Servis/guncelleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.guncelleResponse guncelle(WindowsFormsApplication12.ServiceReference1.guncelleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/Yer_AyirtRequest", ReplyAction="http://cehars/Yeni_Web_Servis/Yer_AyirtResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.Yer_AyirtResponse Yer_Ayirt(WindowsFormsApplication12.ServiceReference1.Yer_AyirtRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/onayRequest", ReplyAction="http://cehars/Yeni_Web_Servis/onayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.onayResponse onay(WindowsFormsApplication12.ServiceReference1.onayRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/listele_isimRequest", ReplyAction="http://cehars/Yeni_Web_Servis/listele_isimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.listele_isimResponse listele_isim(WindowsFormsApplication12.ServiceReference1.listele_isimRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/listele_bosRequest", ReplyAction="http://cehars/Yeni_Web_Servis/listele_bosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.listele_bosResponse listele_bos(WindowsFormsApplication12.ServiceReference1.listele_bosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/kayit_silRequest", ReplyAction="http://cehars/Yeni_Web_Servis/kayit_silResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.kayit_silResponse kayit_sil(WindowsFormsApplication12.ServiceReference1.kayit_silRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/onay2Request", ReplyAction="http://cehars/Yeni_Web_Servis/onay2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.onay2Response onay2(WindowsFormsApplication12.ServiceReference1.onay2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/onay3Request", ReplyAction="http://cehars/Yeni_Web_Servis/onay3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.onay3Response onay3(WindowsFormsApplication12.ServiceReference1.onay3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/doluluk_durumuRequest", ReplyAction="http://cehars/Yeni_Web_Servis/doluluk_durumuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.doluluk_durumuResponse doluluk_durumu(WindowsFormsApplication12.ServiceReference1.doluluk_durumuRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/listele_fiyatRequest", ReplyAction="http://cehars/Yeni_Web_Servis/listele_fiyatResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication12.ServiceReference1.listele_fiyatResponse listele_fiyat(WindowsFormsApplication12.ServiceReference1.listele_fiyatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ekle", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class ekleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiyat;
        
        public ekleRequest() {
        }
        
        public ekleRequest(string otel_ismi, string fiyat) {
            this.otel_ismi = otel_ismi;
            this.fiyat = fiyat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ekleResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class ekleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ekleResponse() {
        }
        
        public ekleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sorgu", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class sorguRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public sorguRequest() {
        }
        
        public sorguRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sorguResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class sorguResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sorguResponse() {
        }
        
        public sorguResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guncelle", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class guncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiyat;
        
        public guncelleRequest() {
        }
        
        public guncelleRequest(string otel_ismi, string fiyat) {
            this.otel_ismi = otel_ismi;
            this.fiyat = fiyat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guncelleResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class guncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public guncelleResponse() {
        }
        
        public guncelleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Yer_Ayirt", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class Yer_AyirtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kisi;
        
        public Yer_AyirtRequest() {
        }
        
        public Yer_AyirtRequest(string otel_ismi, string kisi) {
            this.otel_ismi = otel_ismi;
            this.kisi = kisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Yer_AyirtResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class Yer_AyirtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public Yer_AyirtResponse() {
        }
        
        public Yer_AyirtResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onay", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kac_kisi;
        
        public onayRequest() {
        }
        
        public onayRequest(string otel_ismi, string kac_kisi) {
            this.otel_ismi = otel_ismi;
            this.kac_kisi = kac_kisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onayResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public onayResponse() {
        }
        
        public onayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_isim", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_isimRequest {
        
        public listele_isimRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_isimResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_isimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public listele_isimResponse() {
        }
        
        public listele_isimResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_bos", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_bosRequest {
        
        public listele_bosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_bosResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_bosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public listele_bosResponse() {
        }
        
        public listele_bosResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kayit_sil", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class kayit_silRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public kayit_silRequest() {
        }
        
        public kayit_silRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kayit_silResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class kayit_silResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public kayit_silResponse() {
        }
        
        public kayit_silResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onay2", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onay2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kac_kisi;
        
        public onay2Request() {
        }
        
        public onay2Request(string otel_ismi, string kac_kisi) {
            this.otel_ismi = otel_ismi;
            this.kac_kisi = kac_kisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onay2Response", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onay2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public onay2Response() {
        }
        
        public onay2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onay3", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onay3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kac_kisi;
        
        public onay3Request() {
        }
        
        public onay3Request(string otel_ismi, string kac_kisi) {
            this.otel_ismi = otel_ismi;
            this.kac_kisi = kac_kisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onay3Response", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class onay3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public onay3Response() {
        }
        
        public onay3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doluluk_durumu", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class doluluk_durumuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public doluluk_durumuRequest() {
        }
        
        public doluluk_durumuRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doluluk_durumuResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class doluluk_durumuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public doluluk_durumuResponse() {
        }
        
        public doluluk_durumuResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_fiyat", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_fiyatRequest {
        
        public listele_fiyatRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_fiyatResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_fiyatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public listele_fiyatResponse() {
        }
        
        public listele_fiyatResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Yeni_Web_ServisChannel : WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Yeni_Web_ServisClient : System.ServiceModel.ClientBase<WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis>, WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis {
        
        public Yeni_Web_ServisClient() {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.ekleResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.ekle(WindowsFormsApplication12.ServiceReference1.ekleRequest request) {
            return base.Channel.ekle(request);
        }
        
        public string ekle(string otel_ismi, string fiyat) {
            WindowsFormsApplication12.ServiceReference1.ekleRequest inValue = new WindowsFormsApplication12.ServiceReference1.ekleRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.fiyat = fiyat;
            WindowsFormsApplication12.ServiceReference1.ekleResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).ekle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.sorguResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.sorgu(WindowsFormsApplication12.ServiceReference1.sorguRequest request) {
            return base.Channel.sorgu(request);
        }
        
        public string sorgu(string otel_ismi) {
            WindowsFormsApplication12.ServiceReference1.sorguRequest inValue = new WindowsFormsApplication12.ServiceReference1.sorguRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication12.ServiceReference1.sorguResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).sorgu(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.guncelleResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.guncelle(WindowsFormsApplication12.ServiceReference1.guncelleRequest request) {
            return base.Channel.guncelle(request);
        }
        
        public string guncelle(string otel_ismi, string fiyat) {
            WindowsFormsApplication12.ServiceReference1.guncelleRequest inValue = new WindowsFormsApplication12.ServiceReference1.guncelleRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.fiyat = fiyat;
            WindowsFormsApplication12.ServiceReference1.guncelleResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).guncelle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.Yer_AyirtResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.Yer_Ayirt(WindowsFormsApplication12.ServiceReference1.Yer_AyirtRequest request) {
            return base.Channel.Yer_Ayirt(request);
        }
        
        public string Yer_Ayirt(string otel_ismi, string kisi) {
            WindowsFormsApplication12.ServiceReference1.Yer_AyirtRequest inValue = new WindowsFormsApplication12.ServiceReference1.Yer_AyirtRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.kisi = kisi;
            WindowsFormsApplication12.ServiceReference1.Yer_AyirtResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).Yer_Ayirt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.onayResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.onay(WindowsFormsApplication12.ServiceReference1.onayRequest request) {
            return base.Channel.onay(request);
        }
        
        public string onay(string otel_ismi, string kac_kisi) {
            WindowsFormsApplication12.ServiceReference1.onayRequest inValue = new WindowsFormsApplication12.ServiceReference1.onayRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.kac_kisi = kac_kisi;
            WindowsFormsApplication12.ServiceReference1.onayResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).onay(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.listele_isimResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.listele_isim(WindowsFormsApplication12.ServiceReference1.listele_isimRequest request) {
            return base.Channel.listele_isim(request);
        }
        
        public string[] listele_isim() {
            WindowsFormsApplication12.ServiceReference1.listele_isimRequest inValue = new WindowsFormsApplication12.ServiceReference1.listele_isimRequest();
            WindowsFormsApplication12.ServiceReference1.listele_isimResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).listele_isim(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.listele_bosResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.listele_bos(WindowsFormsApplication12.ServiceReference1.listele_bosRequest request) {
            return base.Channel.listele_bos(request);
        }
        
        public string[] listele_bos() {
            WindowsFormsApplication12.ServiceReference1.listele_bosRequest inValue = new WindowsFormsApplication12.ServiceReference1.listele_bosRequest();
            WindowsFormsApplication12.ServiceReference1.listele_bosResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).listele_bos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.kayit_silResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.kayit_sil(WindowsFormsApplication12.ServiceReference1.kayit_silRequest request) {
            return base.Channel.kayit_sil(request);
        }
        
        public string kayit_sil(string otel_ismi) {
            WindowsFormsApplication12.ServiceReference1.kayit_silRequest inValue = new WindowsFormsApplication12.ServiceReference1.kayit_silRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication12.ServiceReference1.kayit_silResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).kayit_sil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.onay2Response WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.onay2(WindowsFormsApplication12.ServiceReference1.onay2Request request) {
            return base.Channel.onay2(request);
        }
        
        public string onay2(string otel_ismi, string kac_kisi) {
            WindowsFormsApplication12.ServiceReference1.onay2Request inValue = new WindowsFormsApplication12.ServiceReference1.onay2Request();
            inValue.otel_ismi = otel_ismi;
            inValue.kac_kisi = kac_kisi;
            WindowsFormsApplication12.ServiceReference1.onay2Response retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).onay2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.onay3Response WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.onay3(WindowsFormsApplication12.ServiceReference1.onay3Request request) {
            return base.Channel.onay3(request);
        }
        
        public string onay3(string otel_ismi, string kac_kisi) {
            WindowsFormsApplication12.ServiceReference1.onay3Request inValue = new WindowsFormsApplication12.ServiceReference1.onay3Request();
            inValue.otel_ismi = otel_ismi;
            inValue.kac_kisi = kac_kisi;
            WindowsFormsApplication12.ServiceReference1.onay3Response retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).onay3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.doluluk_durumuResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.doluluk_durumu(WindowsFormsApplication12.ServiceReference1.doluluk_durumuRequest request) {
            return base.Channel.doluluk_durumu(request);
        }
        
        public string doluluk_durumu(string otel_ismi) {
            WindowsFormsApplication12.ServiceReference1.doluluk_durumuRequest inValue = new WindowsFormsApplication12.ServiceReference1.doluluk_durumuRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication12.ServiceReference1.doluluk_durumuResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).doluluk_durumu(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication12.ServiceReference1.listele_fiyatResponse WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis.listele_fiyat(WindowsFormsApplication12.ServiceReference1.listele_fiyatRequest request) {
            return base.Channel.listele_fiyat(request);
        }
        
        public string[] listele_fiyat() {
            WindowsFormsApplication12.ServiceReference1.listele_fiyatRequest inValue = new WindowsFormsApplication12.ServiceReference1.listele_fiyatRequest();
            WindowsFormsApplication12.ServiceReference1.listele_fiyatResponse retVal = ((WindowsFormsApplication12.ServiceReference1.Yeni_Web_Servis)(this)).listele_fiyat(inValue);
            return retVal.@return;
        }
    }
}
