//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cehars/", ConfigurationName="ServiceReference1.Yeni_Web_Servis")]
    public interface Yeni_Web_Servis {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/bos_bulRequest", ReplyAction="http://cehars/Yeni_Web_Servis/bos_bulResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.bos_bulResponse bos_bul(WindowsFormsApplication15.ServiceReference1.bos_bulRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/silRequest", ReplyAction="http://cehars/Yeni_Web_Servis/silResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.silResponse sil(WindowsFormsApplication15.ServiceReference1.silRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/fiyat_bulRequest", ReplyAction="http://cehars/Yeni_Web_Servis/fiyat_bulResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.fiyat_bulResponse fiyat_bul(WindowsFormsApplication15.ServiceReference1.fiyat_bulRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/helloRequest", ReplyAction="http://cehars/Yeni_Web_Servis/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.helloResponse hello(WindowsFormsApplication15.ServiceReference1.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/listele_isimRequest", ReplyAction="http://cehars/Yeni_Web_Servis/listele_isimResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.listele_isimResponse listele_isim(WindowsFormsApplication15.ServiceReference1.listele_isimRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/ekleRequest", ReplyAction="http://cehars/Yeni_Web_Servis/ekleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.ekleResponse ekle(WindowsFormsApplication15.ServiceReference1.ekleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cehars/Yeni_Web_Servis/guncelleRequest", ReplyAction="http://cehars/Yeni_Web_Servis/guncelleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApplication15.ServiceReference1.guncelleResponse guncelle(WindowsFormsApplication15.ServiceReference1.guncelleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bos_bul", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class bos_bulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public bos_bulRequest() {
        }
        
        public bos_bulRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bos_bulResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class bos_bulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public bos_bulResponse() {
        }
        
        public bos_bulResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sil", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class silRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public silRequest() {
        }
        
        public silRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="silResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class silResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public silResponse() {
        }
        
        public silResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fiyat_bul", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class fiyat_bulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        public fiyat_bulRequest() {
        }
        
        public fiyat_bulRequest(string otel_ismi) {
            this.otel_ismi = otel_ismi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fiyat_bulResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class fiyat_bulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public fiyat_bulResponse() {
        }
        
        public fiyat_bulResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_isim", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_isimRequest {
        
        public listele_isimRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listele_isimResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class listele_isimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public listele_isimResponse() {
        }
        
        public listele_isimResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ekle", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class ekleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiyat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bos;
        
        public ekleRequest() {
        }
        
        public ekleRequest(string otel_ismi, string fiyat, string bos) {
            this.otel_ismi = otel_ismi;
            this.fiyat = fiyat;
            this.bos = bos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ekleResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class ekleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ekleResponse() {
        }
        
        public ekleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guncelle", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class guncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string otel_ismi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiyat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bos;
        
        public guncelleRequest() {
        }
        
        public guncelleRequest(string otel_ismi, string fiyat, string bos) {
            this.otel_ismi = otel_ismi;
            this.fiyat = fiyat;
            this.bos = bos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guncelleResponse", WrapperNamespace="http://cehars/", IsWrapped=true)]
    public partial class guncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cehars/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public guncelleResponse() {
        }
        
        public guncelleResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Yeni_Web_ServisChannel : WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Yeni_Web_ServisClient : System.ServiceModel.ClientBase<WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis>, WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis {
        
        public Yeni_Web_ServisClient() {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yeni_Web_ServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.bos_bulResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.bos_bul(WindowsFormsApplication15.ServiceReference1.bos_bulRequest request) {
            return base.Channel.bos_bul(request);
        }
        
        public string bos_bul(string otel_ismi) {
            WindowsFormsApplication15.ServiceReference1.bos_bulRequest inValue = new WindowsFormsApplication15.ServiceReference1.bos_bulRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication15.ServiceReference1.bos_bulResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).bos_bul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.silResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.sil(WindowsFormsApplication15.ServiceReference1.silRequest request) {
            return base.Channel.sil(request);
        }
        
        public string sil(string otel_ismi) {
            WindowsFormsApplication15.ServiceReference1.silRequest inValue = new WindowsFormsApplication15.ServiceReference1.silRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication15.ServiceReference1.silResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).sil(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.fiyat_bulResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.fiyat_bul(WindowsFormsApplication15.ServiceReference1.fiyat_bulRequest request) {
            return base.Channel.fiyat_bul(request);
        }
        
        public string fiyat_bul(string otel_ismi) {
            WindowsFormsApplication15.ServiceReference1.fiyat_bulRequest inValue = new WindowsFormsApplication15.ServiceReference1.fiyat_bulRequest();
            inValue.otel_ismi = otel_ismi;
            WindowsFormsApplication15.ServiceReference1.fiyat_bulResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).fiyat_bul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.helloResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.hello(WindowsFormsApplication15.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WindowsFormsApplication15.ServiceReference1.helloRequest inValue = new WindowsFormsApplication15.ServiceReference1.helloRequest();
            inValue.name = name;
            WindowsFormsApplication15.ServiceReference1.helloResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.listele_isimResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.listele_isim(WindowsFormsApplication15.ServiceReference1.listele_isimRequest request) {
            return base.Channel.listele_isim(request);
        }
        
        public string[] listele_isim() {
            WindowsFormsApplication15.ServiceReference1.listele_isimRequest inValue = new WindowsFormsApplication15.ServiceReference1.listele_isimRequest();
            WindowsFormsApplication15.ServiceReference1.listele_isimResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).listele_isim(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.ekleResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.ekle(WindowsFormsApplication15.ServiceReference1.ekleRequest request) {
            return base.Channel.ekle(request);
        }
        
        public string ekle(string otel_ismi, string fiyat, string bos) {
            WindowsFormsApplication15.ServiceReference1.ekleRequest inValue = new WindowsFormsApplication15.ServiceReference1.ekleRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.fiyat = fiyat;
            inValue.bos = bos;
            WindowsFormsApplication15.ServiceReference1.ekleResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).ekle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication15.ServiceReference1.guncelleResponse WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis.guncelle(WindowsFormsApplication15.ServiceReference1.guncelleRequest request) {
            return base.Channel.guncelle(request);
        }
        
        public string guncelle(string otel_ismi, string fiyat, string bos) {
            WindowsFormsApplication15.ServiceReference1.guncelleRequest inValue = new WindowsFormsApplication15.ServiceReference1.guncelleRequest();
            inValue.otel_ismi = otel_ismi;
            inValue.fiyat = fiyat;
            inValue.bos = bos;
            WindowsFormsApplication15.ServiceReference1.guncelleResponse retVal = ((WindowsFormsApplication15.ServiceReference1.Yeni_Web_Servis)(this)).guncelle(inValue);
            return retVal.@return;
        }
    }
}
